# Generated by Django 3.2.8 on 2021-10-14 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import userextended.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_extended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ImageField(upload_to=userextended.models.user_extended.get_user_name)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=225)),
                ('country', models.CharField(max_length=225)),
                ('phone_number', models.CharField(max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userextended_user_extended_realted', related_query_name='userextended_user_extendeds', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('user_extended_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
