# Generated by Django 3.2.8 on 2021-10-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextended', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extended',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
