# Generated by Django 3.2.8 on 2021-10-14 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userextended.models
import userextended.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userextended', '0002_alter_user_extended_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extended',
            name='address',
            field=models.CharField(max_length=225, validators=[userextended.validators.charinput_validation]),
        ),
        migrations.AlterField(
            model_name='user_extended',
            name='country',
            field=models.CharField(max_length=225, validators=[userextended.validators.charinput_validation]),
        ),
        migrations.AlterField(
            model_name='user_extended',
            name='date_of_birth',
            field=models.DateField(null=True, validators=[userextended.validators.dob_validation]),
        ),
        migrations.AlterField(
            model_name='user_extended',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[userextended.validators.phone_validation]),
        ),
        migrations.AlterField(
            model_name='user_extended',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userextended_realted', related_query_name='userextended_query', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_extended',
            name='user_profile',
            field=models.ImageField(upload_to=userextended.models.user_extended.get_user_name, validators=[userextended.validators.image_validation]),
        ),
    ]
