# Generated by Django 3.2.8 on 2021-10-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userextended', '0003_auto_20211014_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extended',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userex_realted', related_query_name='userex_query', to=settings.AUTH_USER_MODEL),
        ),
    ]
