# Generated by Django 3.2.8 on 2021-10-14 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userextended', '0004_alter_user_extended_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_extended',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userextended_related', related_query_name='userextended_query', to=settings.AUTH_USER_MODEL),
        ),
    ]
