# Generated by Django 3.2.8 on 2021-10-29 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userextended', '0005_alter_user_extended_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_extended',
            table='Extended',
        ),
    ]
