# Generated by Django 3.2.8 on 2021-10-18 10:59

from django.db import migrations, models
import userextended.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=225, validators=[userextended.validators.charinput_validation])),
            ],
        ),
    ]
