# Generated by Django 3.2.8 on 2021-10-18 10:59

from django.db import migrations, models
import django.db.models.deletion
import userextended.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video', '0001_initial'),
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='palylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, validators=[userextended.validators.charinput_validation])),
                ('is_private', models.BooleanField(default=False)),
                ('channel_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_related', related_query_name='playlist_query', to='channel.channel_model')),
                ('video', models.ManyToManyField(related_name='playlist_video_related', related_query_name='playlist_video_query', to='video.video')),
            ],
        ),
    ]
