# Generated by Django 3.2.8 on 2021-10-20 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watch_later', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='watch_time',
        ),
    ]
