# Generated by Django 3.2.8 on 2021-10-18 10:59

import ads.validators
import channel.validators
from django.db import migrations, models
import django.db.models.deletion
import userextended.validators
import video.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channel', '0001_initial'),
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=225, validators=[userextended.validators.charinput_validation])),
                ('video_thumb_nail', models.ImageField(upload_to=video.models.video.video_tumb_url, validators=[userextended.validators.image_validation])),
                ('video', models.FileField(upload_to=video.models.video.video_url, validators=[ads.validators.video_check])),
                ('video_description', models.TextField(validators=[channel.validators.text_field])),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('cataogories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catagory_realted', related_query_name='catagory_query', to='catagories.catagories')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_related', related_query_name='video_query', to='channel.channel_model')),
            ],
        ),
    ]
