# Generated by Django 3.2.8 on 2021-10-20 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userextended.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.CharField(choices=[('a', 'sexual content'), ('b', 'voliance'), ('c', 'Hate Speech'), ('d', 'Other')], max_length=30, validators=[userextended.validators.charinput_validation])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_user_related', related_query_name='report_user_query', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_video_related', related_query_name='report_video_query', to='video.video')),
            ],
        ),
    ]
