# Generated by Django 3.2.8 on 2021-10-18 10:59

import channel.models
import channel.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userextended.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='channel_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=225, validators=[userextended.validators.charinput_validation])),
                ('channel_description', models.TextField(validators=[channel.validators.text_field])),
                ('channel_cover', models.ImageField(upload_to=channel.models.channel_model.cover_url, validators=[userextended.validators.image_validation])),
                ('channel_picture', models.ImageField(upload_to=channel.models.channel_model.image_url, validators=[userextended.validators.image_validation])),
                ('can_upload_video', models.BooleanField(default=True)),
                ('is_live', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel_realted', related_query_name='channel_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
