# Generated by Django 3.2.8 on 2021-10-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('dilike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like_dislike',
            name='video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_video_related', related_query_name='like_video_query', to='video.video'),
            preserve_default=False,
        ),
    ]
